[workspace]
members = ["tui_glicol", "bevy_glicol", "glicol-cli"]
resolver = "1"

[workspace.package]
version = "0.1.0-dev"
edition = "2021"
repository = "https://github.com/lavaeater/bevy_glicol"
authors = [
    "Tommie Nygren <tommie.nygren@gmail.com>",
    "Qichao Lan <chaosprint@gmail.com>",
]
