[package]
name = "glicol"
version = { workspace = true }
edition = { workspace = true }
keywords = ["audio", "music", "DSP", "synth", "synthesizer"]

license-file = "LICENSE"
description = "Glicol language main entry point."
repository = "https://github.com/chaosprint/glicol.git"
authors = ["Qichao Lan <chaosprint@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
use-samples = []
use-meta = []
bela = []
wasm-bindgen = ["glicol_synth/wasm-bindgen"]

[dependencies]
petgraph = { workspace = true }
glicol_parser = { path = "../parser" }
glicol_synth = { path = "../synth", features = [
    "use-samples",
    "use-meta",
    "node-boxed",
    "node-pass",
    "node-sampling",
    "node-dynamic",
    "node-sum",
], default-features = true }
pest = { workspace = true }
hashbrown = { workspace = true }
yoke = { workspace = true }

[dev-dependencies]
gnuplot = "0.0.45"
# petgraph = { version = "0.6",  features = ["stable_graph"] }
# cpal = "0.15.3"
anyhow = "1.0.63"
