[package]
name = "glicol_parser"
version = { workspace = true }
edition = { workspace = true }
keywords = ["audio", "music", "DSP", "synth", "synthesizer"]

license-file = "LICENSE"
description = "Parser for Glicol language."
repository = "https://github.com/chaosprint/glicol.git"
authors = ["Qichao Lan <chaosprint@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = { workspace = true }
pest_derive = { workspace = true }
hashbrown = { workspace = true }
fasteval = { workspace = true }
yoke = { workspace = true }

[dev-dependencies]
trace = "0.1.7"
